// <auto-generated />
using FirstRESTApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstRESTApi.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20250708102734_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("FirstRESTApi.Model.Playlist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("FirstRESTApi.Model.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Playlistid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Playlistid");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("FirstRESTApi.Model.Song", b =>
                {
                    b.HasOne("FirstRESTApi.Model.Playlist", null)
                        .WithMany("songs")
                        .HasForeignKey("Playlistid");
                });

            modelBuilder.Entity("FirstRESTApi.Model.Playlist", b =>
                {
                    b.Navigation("songs");
                });
#pragma warning restore 612, 618
        }
    }
}
